// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/asynccnu/be-infoSum/grpc"
	"github.com/asynccnu/be-infoSum/ioc"
	"github.com/asynccnu/be-infoSum/pkg/grpcx"
	"github.com/asynccnu/be-infoSum/repository/cache"
	"github.com/asynccnu/be-infoSum/repository/dao"
	"github.com/asynccnu/be-infoSum/service"
)

// Injectors from wire.go:

func InitGRPCServer() grpcx.Server {
	logger := ioc.InitLogger()
	db := ioc.InitDB(logger)
	infoSumDAO := dao.NewMysqlInfoSumDAO(db)
	cmdable := ioc.InitRedis()
	infoSumCache := cache.NewRedisInfoSumCache(cmdable)
	infoSumService := service.NewInfoSumService(infoSumDAO, infoSumCache, logger)
	infoSumServiceServer := grpc.NewInfoSumServiceServer(infoSumService)
	client := ioc.InitEtcdClient()
	server := ioc.InitGRPCxKratosServer(infoSumServiceServer, client, logger)
	return server
}
